version: '3.9'

services:
  backend:
    build:
      context: ./backend/
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend/
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
