version: '3.9'

services:
  db:
    image: postgres:15
    platform: linux/amd64
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - heart-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_DB
    user: postgres
    restart: always

  backend:
    build:
      context: ./backend/
    env_file: .env
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./backend:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 1337:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend

volumes:
  heart-database:
    external: true
  static:
  media:
