# Generated by Django 4.2.16 on 2025-02-23 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "analysis",
            "0003_babloodanalysis_ecganalysis_oakanalysis_oamanalysis_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="babloodanalysis",
            options={"verbose_name": "БХ Крови", "verbose_name_plural": "БХ Крови"},
        ),
        migrations.AlterModelOptions(
            name="ecganalysis",
            options={"verbose_name": "ЭКГ", "verbose_name_plural": "ЭКГ"},
        ),
        migrations.AlterModelOptions(
            name="oakanalysis",
            options={"verbose_name": "ОАК", "verbose_name_plural": "ОАК"},
        ),
        migrations.AlterModelOptions(
            name="oamanalysis",
            options={"verbose_name": "ОАМ", "verbose_name_plural": "ОАМ"},
        ),
        migrations.AlterField(
            model_name="babloodanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="ecganalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="oakanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="oamanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
