# Generated by Django 4.2.16 on 2025-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_babloodanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babloodanalysis',
            name='disease_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='код заболевания (по МКБ-10)'),
        ),
        migrations.AddField(
            model_name='ecganalysis',
            name='disease_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='код заболевания (по МКБ-10)'),
        ),
        migrations.AddField(
            model_name='oakanalysis',
            name='disease_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='код заболевания (по МКБ-10)'),
        ),
        migrations.AddField(
            model_name='oamanalysis',
            name='disease_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='код заболевания (по МКБ-10)'),
        ),
    ]
