# Generated by Django 4.2.16 on 2025-09-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="название")),
                ("address", models.CharField(max_length=200, verbose_name="адрес")),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="номер телефона"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="веб-сайт"),
                ),
            ],
            options={
                "verbose_name": "медицинское учреждение",
                "verbose_name_plural": "медицинские учреждения",
            },
        ),
    ]
