# Generated by Django 4.2.16 on 2025-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalinstitution",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="электронная почта"
            ),
        ),
    ]
