# Generated by Django 4.2.16 on 2024-11-24 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacienteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="вес"
                    ),
                ),
                (
                    "systolic_blood_pressure",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="систолическое артериальное давление",
                    ),
                ),
                (
                    "diastolic_blood_pressure",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="диастолическое артериальное давление",
                    ),
                ),
                (
                    "health_status",
                    models.TextField(blank=True, null=True, verbose_name="состояние"),
                ),
                (
                    "skin_and_mucous_membrane",
                    models.TextField(
                        blank=True, null=True, verbose_name="кожа и слизистая оболочка"
                    ),
                ),
                (
                    "subcutaneous_fat",
                    models.TextField(
                        blank=True, null=True, verbose_name="подкожно-жировая клетчатка"
                    ),
                ),
                (
                    "lymphatic_system",
                    models.TextField(
                        blank=True, null=True, verbose_name="лимфатическая система"
                    ),
                ),
                (
                    "musculoskeletal_system",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="опорно-двигательная система",
                    ),
                ),
                (
                    "respiratory_system",
                    models.TextField(
                        blank=True, null=True, verbose_name="дыхательная система"
                    ),
                ),
                (
                    "cardiovascular_system",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="сердечно-сосудистая система",
                    ),
                ),
                (
                    "digestive_system",
                    models.TextField(
                        blank=True, null=True, verbose_name="пищеварительная система"
                    ),
                ),
                (
                    "genitourinary_system",
                    models.TextField(
                        blank=True, null=True, verbose_name="мочеполовая система"
                    ),
                ),
                (
                    "endocrine_system",
                    models.TextField(
                        blank=True, null=True, verbose_name="эндокринная система"
                    ),
                ),
                (
                    "nervous_system",
                    models.TextField(
                        blank=True, null=True, verbose_name="нервная система"
                    ),
                ),
                (
                    "past_illnesses",
                    models.TextField(
                        blank=True, null=True, verbose_name="перенесенные заболевания"
                    ),
                ),
                (
                    "disability",
                    models.BooleanField(default=False, verbose_name="инвалидность"),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="образование",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="профессия"
                    ),
                ),
                (
                    "family_status",
                    models.CharField(
                        blank=True,
                        choices=[("married", "женат"), ("not_married", "не женат")],
                        max_length=11,
                        null=True,
                        verbose_name="семейный статус",
                    ),
                ),
                (
                    "has_children",
                    models.BooleanField(default=False, verbose_name="есть дети"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="ЛПУ"
                    ),
                ),
                (
                    "subdivision",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="подразделение",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="дата рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False, verbose_name="врач"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_nurse",
            field=models.BooleanField(
                default=False, verbose_name="средний медперсонал"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("m", "мужской"), ("w", "женский")],
                default="m",
                max_length=10,
                verbose_name="пол",
            ),
        ),
    ]
