# Generated by Django 4.2.16 on 2025-02-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0002_pacienteprofile_personalprofile_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteprofile',
            options={'verbose_name': 'профиль пациента', 'verbose_name_plural': 'профили пациентов'},
        ),
        migrations.AlterModelOptions(
            name='personalprofile',
            options={'verbose_name': 'профиль персонала', 'verbose_name_plural': 'профили персонала'},
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
