# Generated by Django 4.2.16 on 2025-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_pacienteprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteprofile',
            name='cmi_policy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='полис ОМС'),
        ),
        migrations.AddField(
            model_name='pacienteprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='рост'),
        ),
        migrations.AddField(
            model_name='pacienteprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='номер паспорта'),
        ),
        migrations.AddField(
            model_name='pacienteprofile',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='серия паспорта'),
        ),
        migrations.AddField(
            model_name='pacienteprofile',
            name='registration',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='прописка (по паспорту)'),
        ),
    ]
