# Generated by Django 4.2.16 on 2025-09-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical_institutions", "0001_initial"),
        ("user", "0004_pacienteprofile_cmi_policy_pacienteprofile_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalprofile",
            name="institution",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal",
                to="medical_institutions.medicalinstitution",
                verbose_name="медицинское учреждение",
            ),
            preserve_default=False,
        ),
    ]
